# Generated by Django 5.0.6 on 2024-05-17 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_reserva_am_pm'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='am_pm',
        ),
        migrations.AddField(
            model_name='reserva',
            name='jornada',
            field=models.CharField(choices=[('AM', 'AM'), ('PM', 'PM')], default='AM', max_length=2),
        ),
    ]
